### ISSUE TITLE
No markers in localite

### ISSUE THREAD

**Issue by GerJuli** [pyreiz/ctrl-localite#2] opened 2019-10-16 07:07 UTC
During hotspot search it is often the case that localite does not update the stimulation list. It still sends markers (containing position and responses) to the python environment. It is then possible to open the collection and manually type in the position of a stimulus.

**Comment by GerJuli** [comment] 2019-10-25 12:42
This was solved by fixing the connection between localite and control computer.
Yet the function localite.response.get_latency() produces negative values that are forwarded to the json-sting that is send to localite. Localite awaits only positiv values.

**Comment by agricolab** [comment] 2020-02-03 12:06
We do not test during setting the response  (see https://github.com/pyreiz/ctrl-localite/blob/master localite/coil.py#L209), but the mock localite server was updated to implement the desired behaviour https://github.com/pyreiz/ctrl-localite/blob/master/localite/flow/mock.py#L162

**Comment by agricolab** [comment] 2020-03-05 17:17
Considering that the bug was caused by a loose BNC and that the other aspect, i.e. negative values, are now checked from the clients sides in the most recent release , i guess we can close this issue. Additionally, i informed the company about this unexpected behavior of accepting negative values..

**Closed by agricolab** 2020-03-05 17:17 UTC
